const orderProducts = [
  {
    name: "Product1",
    showIcon: "../assets/icon/shopping-cart.svg",
    shopText: "1",
    loveIcon: "../assets/icon/love.svg",
    foodImage: "../assets/images/yellow-colbasa.png",
    foodPrice: "77,99",
    foodDescription: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    buyBtn: "В корзину",
  },
  {
    name: "Product2",
    showIcon: "../assets/icon/shopping-cart.svg",
    shopText: "2",
    loveIcon: "../assets/icon/love.svg",
    foodImage: "../assets/images/food-four.png",
    foodPrice: "159,99",
    foodDescription: "Комбайн КЗС-1219 «ДЕСНА-ПОЛЕСЬЕ GS13»",
    buyBtn: "В корзину",
  },
  {
    name: "Product3",
    showIcon: "../assets/icon/shopping-cart.svg",
    shopText: "3",
    loveIcon: "../assets/icon/love.svg",
    foodImage: "../assets/images/food-three.png",
    foodPrice: "49,39",
    foodDescription: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    buyBtn: "В корзину",
  },
  {
    name: "Product4",
    showIcon: "../assets/icon/shopping-cart.svg",
    shopText: "4",
    loveIcon: "../assets/icon/love.svg",
    foodImage: "../assets/images/black-colbasa.png",
    foodPrice: "599,99",
    foodDescription: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    buyBtn: "В корзину",
  },
  {
    name: "Product5",
    showIcon: "../assets/icon/shopping-cart.svg",
    shopText: "5",
    loveIcon: "../assets/icon/love.svg",
    foodImage: "../assets/images/yellow-colbasa.png",
    foodPrice: "599,99",
    foodDescription: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    buyBtn: "В корзину",
  },
  {
    name: "Product6",
    showIcon: "../assets/icon/shopping-cart.svg",
    shopText: "6",
    loveIcon: "../assets/icon/love.svg",
    foodImage: "../assets/images/food-two.png",
    foodPrice: "599,99",
    foodDescription: "Комбайн КЗС-1218 «ДЕСНА-ПОЛЕСЬЕ GS12»",
    buyBtn: "В корзину",
  },
];
